# MySQL ????
canal.instance.master.address=ruoyi-mysql:3306
canal.instance.dbUsername=root
canal.instance.dbPassword=password
canal.instance.connectionCharset=UTF-8

# binlog ??
canal.instance.defaultDatabaseName=ry-cloud
canal.instance.filter.regex=ry-cloud\\.sys_notice

# ????
canal.instance.tsdb.enable=true